@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package dev.chouten.runners.relay

import com.fleeksoft.ksoup.Ksoup
import com.fleeksoft.ksoup.nodes.Document
import com.fleeksoft.ksoup.nodes.Element
import dev.chouten.core.repository.httpClient
import io.ktor.client.request.request
import io.ktor.client.statement.bodyAsText
import io.ktor.http.HttpMethod
import kotlinx.cinterop.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import relay.*  // Generated by cinterop from relay.def
import platform.posix.size_t
import kotlin.concurrent.AtomicInt

// Pointer to the currently loaded WASM module (managed by C++ code)
private var modulePtr: COpaquePointer? = null
private val responseArena = Arena()

typealias HostRequestFn = CPointer<CFunction<(
    url: CPointer<ByteVar>?,
    len: ULong,
    method: Int,
    out_len: CPointer<UIntVar>?
) -> CPointer<ByteVar>?>>

typealias HostNodeTextFn = CPointer<CFunction<(
    nodeId: ULong,
    out_len: CPointer<UIntVar>?
) -> CPointer<ByteVar>?>>

/**
 * iOS implementation of NativeBridge using cinterop bindings.
 *
 * Calls into C functions defined in relay_c_api.h:
 * - relay_create_module(): Creates a Wasm3Module from WASM bytes
 * - relay_add(): Calls the "add" function in the loaded WASM
 * - relay_set_logger(): Sets a callback for WASM log messages
 * - relay_destroy_module(): Cleans up the module
 */
actual object NativeBridge {
    private val nextId = AtomicInt(1)
    private val documents = mutableMapOf<Int, Document>()
    private val elements = mutableMapOf<Int, Element>()

    val requestHandler: HostRequestFn = staticCFunction {
            url: CPointer<ByteVar>?,
            len: ULong,
            method: Int,
            out_len: CPointer<UIntVar>?
        ->
        // Convert C string to Kotlin String
        val urlString = url?.readBytes(len.toInt())?.decodeToString() ?: ""

        // Call your request function with the parameters
        val response = request(urlString, method)

        // Convert response to C string
        responseArena.clear()
        val responseBytes = response.encodeToByteArray()
        val cString = responseArena.allocArray<ByteVar>(responseBytes.size + 1)

        // Copy bytes one by one
        for (i in responseBytes.indices) {
            cString[i] = responseBytes[i]
        }
        cString[responseBytes.size] = 0.toByte() // Null terminator

        // Set output length
        out_len?.pointed?.value = responseBytes.size.toUInt()

        cString
    }

    val htmlParseHandler = staticCFunction { html: CPointer<ByteVar>?, len: ULong ->
        val rawHtml = html?.readBytes(len.toInt())?.decodeToString() ?: ""
        println("[htmlParse] Raw HTML length: ${rawHtml.length}")

        val htmlString = rawHtml
            .replace("\\&quot;", "\"")
            .replace("&quot;", "\"")
            .replace("\\\"", "\"")
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")

        // The issue is escaped quotes in class attributes
        // Try different parsing options
        val doc = try {
            // Option 1: Parse with different settings
            Ksoup.parse(htmlString)
        } catch (e: Exception) {
            println("[htmlParse] Parse error: ${e.message}")
            return@staticCFunction 0.toUInt()
        }
        println("[htmlParse] Document:\n${doc.html()}");

        println("[htmlParse] Document parsed, text length: ${doc.text().length}")

        // Test if selectors work
        val testTitle = doc.selectFirst(".title")
        val testByAttr = doc.select("*").firstOrNull { it.attr("class").contains("title") }

        println("[htmlParse] Test .title selector: ${testTitle != null}")
        println("[htmlParse] Test by attribute: ${testByAttr != null}")

        if (testTitle == null && testByAttr != null) {
            println("[htmlParse] WARNING: CSS selectors are broken, classes are malformed")
            println("[htmlParse] Sample class: '${testByAttr.attr("class")}'")
        }

        val id = nextId.getAndIncrement()
        documents[id] = doc

        return@staticCFunction id.toUInt()
    }

    val querySelectorHandler = staticCFunction { id: ULong, query: CPointer<ByteVar>?, len: ULong ->
        val selectorString = query?.readBytes(len.toInt())?.decodeToString() ?: ""
        println("[querySelector] Selector: '$selectorString'")

        val doc = documents[id.toInt()] ?: return@staticCFunction 0.toUInt()

        // Dump the actual HTML structure
        println("[querySelector] === DOCUMENT HTML (first 2000 chars) ===")
        println(doc.html().take(2000))
        println("[querySelector] === END HTML ===")

        // Check all elements with class attribute
        val elementsWithClass = doc.select("[class]")
        println("[querySelector] Elements with class attribute: ${elementsWithClass.size}")

        if (elementsWithClass.isNotEmpty()) {
            println("[querySelector] First 10 elements with classes:")
            elementsWithClass.take(10).forEach {
                println("  - <${it.tagName()}> classes: ${it.classNames()}")
            }
        }

        // Check if "title" appears anywhere in class names
        val titleElements = doc.select("*").filter {
            it.classNames().any { cls -> cls.contains("title", ignoreCase = true) }
        }
        println("[querySelector] Elements with 'title' in class name: ${titleElements.size}")

        // Try attribute selector
        val byAttribute = doc.select("[class*=title]")
        println("[querySelector] By attribute [class*=title]: ${byAttribute.size}")

        val element = doc.selectFirst(selectorString)

        if (element == null) {
            println("[querySelector] No match for '$selectorString'")
            return@staticCFunction 0.toUInt()
        }

        println("[querySelector] Found: ${element.text()}")

        val elementId = nextId.getAndIncrement()
        elements[elementId] = element
        return@staticCFunction elementId.toUInt()
    }

    val nodeTextHandler: HostNodeTextFn = staticCFunction { id, out_len ->
        val element = elements[id.toInt()]
        val retString =  element?.text() ?: "Failed."
        println("[nodeText] Text is $retString")

        responseArena.clear()
        val responseBytes = retString.encodeToByteArray()
        val cString = responseArena.allocArray<ByteVar>(responseBytes.size + 1)
        for (i in responseBytes.indices) {
            cString[i] = responseBytes[i]
        }
        cString[responseBytes.size] = 0.toByte() // Null terminator

        // Set output length
        out_len?.pointed?.value = responseBytes.size.toUInt()

        cString
    }

    actual fun request(url: String, method: Int): String {
        println("Requesting url: $url, method: $method")

        return runBlocking {
            val response = withContext(Dispatchers.IO) {
                httpClient.request(url) {
                    // Configure your request here
                    this.method = when (method) {
                        0 -> HttpMethod.Get
                        1 -> HttpMethod.Post
                        // Add other methods as needed
                        else -> HttpMethod.Get
                    }
                }
            }

            val httpResponse = HttpResponse(
                statusCode = response.status.value,
                body = response.bodyAsText(),
                headers = emptyMap()//response.headers.toMap(),
            )
            println("Response -> $httpResponse")

            val jsonString = Json.encodeToString(httpResponse)
            println("JSON Length: ${jsonString.length}")  // Debug
            jsonString
        }
    }

    actual fun callMethod(name: String): String {
        val ptr = modulePtr ?: run {
            RelayLogger.log("RelayWASM -> callMethod: no module loaded")
            return ""
        }
        val result = relay_callMethod(ptr, name)
        return result?.toKString() ?: run {
            RelayLogger.log("RelayWASM -> callMethod '$name' returned null (function lookup failed)")
            ""
        }
    }

    /**
     * Load a WASM module from raw bytes.
     * Uses usePinned to prevent GC from moving the byte array while C is reading it.
     */
    actual fun load(bytes: ByteArray) {
        // Destroy previous module if exists
        modulePtr?.let { relay_destroy_module(it) }

        // Pin the byte array in memory so C can safely read it
        bytes.usePinned { pinned ->
            modulePtr = relay_create_module(
                pinned.addressOf(0).reinterpret(),  // Convert to C pointer type
                bytes.size.convert<size_t>()         // Convert Int to size_t
            )
        }

        relay_set_request_handler(requestHandler)
        relay_set_html_parse_handler(htmlParseHandler)
        relay_set_query_selector_handler(querySelectorHandler)
        relay_set_node_text_handler(nodeTextHandler)
    }

    /**
     * Call the "add" function in the loaded WASM module.
     * Returns 0 if no module is loaded.
     */
    actual fun add(a: Int, b: Int): Int {
        val ptr = modulePtr ?: return 0
        return relay_add(ptr, a, b)
    }

    /**
     * Initialize the logger callback.
     *
     * Uses staticCFunction to create a C function pointer from a Kotlin lambda.
     * When WASM calls host_log(), it triggers this callback which forwards
     * the message to Kotlin's RelayLogger.
     *
     * Note: The logger parameter is ignored on iOS - we use staticCFunction instead
     * because C can only call static functions, not Kotlin object methods directly.
     */
    actual fun initLogger(logger: Any) {
        relay_set_logger(staticCFunction { msg, len ->
            msg?.let {
                val message = it.readBytes(len.toInt()).decodeToString()
                RelayLogger.log(message)
            }
        })
    }

    actual fun initNativeBridge(nativeBridge: NativeBridge) {}
}